### ISSUE TITLE
`cargo install mdbook-footnote --locked` fails

### ISSUE THREAD

**Issue by max-sixty** [daviddrysdale/mdbook-footnote#1]
Thanks for the library!

Would it be possible to bump `Cargo.lock` and release a new version? Currently installing with those dependencies fails: https://github.com/PRQL/prql/actions/runs/4503756308/jobs/7927364965?pr=2295

**Comment by daviddrysdale** [comment]
Done. 

(By the way, I think you could have worked around this by dropping the `--locked` option in your CI.)

**Comment by max-sixty** [comment]
Thank you!

> (By the way, I think you could have worked around this by dropping the `--locked` option in your CI.)

Yes, thanks, we did this. I'll now revert! :)
